language: java
sudo : false
dist : trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer

before_install:
- rm ~/.m2/settings.xml

env: 
  - MAVEN_SCRIPT="mvn clean install -DskipTests=false -q --update-snapshots -f  ./dhis-2/pom.xml"
  - MAVEN_SCRIPT="mvn clean install -DskipTests=false -q --update-snapshots -f ./dhis-2/dhis-web/pom.xml"
  - MAVEN_SCRIPT="mvn clean install -Pintegration"
  
script: 
 - $MAVEN_SCRIPT
branches:
  only:
  - master
  - "/^2\\.[0-9]{1,}/"
