language: java
sudo : false
dist : trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer

before_install:
- rm ~/.m2/settings.xml

matrix: 
  include:
    -env: MAVEN_SCRIPT="mvn clean install -DskipTests=false -DargLine="-Xmx512m -Xms256m" -q --update-snapshots -f  ./dhis-2/pom.xml"
    -env: MAVEN_SCRIPT="mvn clean install -DskipTests=false -DargLine="-Xmx512m -Xms256m" -q --update-snapshots -f ./dhis-2/dhis-web/pom.xml"
    -env: MAVEN_SCRIPT="mvn clean install -Pintegration"
  
script: 
 - $MAVEN_SCRIPT
branches:
  only:
  - master
  - "/^2\\.[0-9]{1,}/"
