language: java
sudo : false
dist : trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer

before_install:
- rm ~/.m2/settings.xml
  
jobs: 
  include:
    - stage: tests 
      name: unit
      script: 
        - mvn clean install -DskipTests=false -q --update-snapshots -f ./dhis-2/pom.xml
        - mvn clean install -DskipTests=false -q --update-snapshots -f ./dhis-2/dhis-web/pom.xml
        
    - name: integration
      script: 
        - mvn clean install -Pintegration -f ./dhis-2/pom.xml
        
branches:
  only:
  - master
  - "/^2\\.[0-9]{1,}/"
