language: java
sudo: false
dist: trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
before_install:
- rm ~/.m2/settings.xml

jobs:
  include:
  - Build
  - stage: Tests
    name: integration
    script:
    - mvn test -Pintegration -f ./dhis-2/pom.xml

  - name: api
    script:
    - cd dhis-2/dhis-e2e-test
    - docker-compose up -d --build-arg ADDITIONAL_MAVEN_BUILD_ARGS="-q"
    - mvn test -DbaseUrl=http://localhost:8070/api
    - docker-compose down

branches:
  only:
  - master
  - "/^2\\.[0-9]{1,}/"
