version: '3'
services:
  db:
    restart: always
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSOWRD: dhis

  e2e-test-web:
    image: "${IMAGE_NAME}"
    build:
      dockerfile: Dockerfile
      context: ../..
      args:
        ADDITIONAL_MAVEN_BUILD_ARGS: -DskipTests -q
    volumes:
      - ./config/dhis2_home/dhis.conf:/DHIS2_home/dhis.conf
    depends_on:
      - db
    ports:
      - 8070:8080
